# 🎼 ADS Homework A01 - Sharif Music Analysis
**Applied Data Science Course 2026**

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](PASTE_YOUR_COLAB_URL_HERE)
[![View on GitHub](https://img.shields.io/badge/GitHub-View_Repository-blue?logo=GitHub)](PASTE_YOUR_GITHUB_URL_HERE)

Welcome to the comprehensive analysis of the Sharif Music telegram group! This notebook explores the interactions, tracks, artists, and sentiments (reflected by interactions/emojis) of users over the past year. 

### 🎯 Objective Overview

#### 1️⃣ Exploratory Data Analysis (EDA) & Cleaning

#### 2️⃣ 📊 Data Visualization

#### 3️⃣ ⚙️ Feature Engineering

#### 4️⃣ 🕸️ Web Scraping (Bonus Task)

---

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# Ignore traditional warnings to keep the notebook readable
import warnings
warnings.filterwarnings('ignore')

# Set visual styles
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams['figure.figsize'] = (10, 6)

print("Libraries imported successfully!")

Libraries imported successfully!

---
#### 1️⃣ Exploratory Data Analysis (EDA) & Cleaning
*   **Comprehensive EDA:** Derive meaningful insights from the interactions, users, and tracks.
*   **Data Cleaning:** Robustly handle missing, invalid, or duplicate values across the dataset.
*   **Preprocessing:** Convert all active features to appropriate numerical representations.
*   **Scaling:** Apply normalization or standardization to set data on comparable scales.
*   **Readability:** Provide clear markdown explanations of all the steps.

## 1. Setup & Data Loading
First, we load the raw datasets extracted from the Telegram channel. We have three main files: `tracks.csv`, `artists.csv`, and `users.csv`.

In [2]:
# Data have to be placed in the data/raw folder
TRACKS_PATH = '../data/raw/tracks.csv'
ARTISTS_PATH = '../data/raw/artists.csv'
USERS_PATH = '../data/raw/users.csv'

try:
    df_tracks = pd.read_csv(TRACKS_PATH)
    df_artists = pd.read_csv(ARTISTS_PATH)
    df_users = pd.read_csv(USERS_PATH)
    
    
    print("✅ Data loaded successfully!\n")
    
    print(f"🎵 Tracks Dataset: {df_tracks.shape[0]} rows, {df_tracks.shape[1]} columns")
    print("Column names:")
    for col in df_tracks.columns:
        print(f"  - {col}")
    print("🔍 Tracks dataset preview:")
    display(df_tracks.head())
    
    print(f"🎤 Artists Dataset: {df_artists.shape[0]} rows, {df_artists.shape[1]} columns")
    print("Column names:")
    for col in df_artists.columns:
        print(f"  - {col}")
    print("🔍 Artists dataset preview:")
    display(df_artists.head())
    
    print(f"👤 Users Dataset: {df_users.shape[0]} rows, {df_users.shape[1]} columns\n")
    print("Column names:")
    for col in df_users.columns:
        print(f"  - {col}")
    print("🔍 Users dataset preview:")
    display(df_users.head())
    
except FileNotFoundError:
    print("⚠️ Raw datasets not found in '../data/raw/'.")

✅ Data loaded successfully!

🎵 Tracks Dataset: 10725 rows, 53 columns
Column names:
  - track_id
  - track_name
  - artist_names
  - artist_count
  - total_likes
  - total_dislikes
  - total_reactions
  - total_comments
  - likes
  - dislikes
  - reactions
  - comments
  - next_track
  - previous_track
  - sender_chat_ids
  - sender_usernames
  - num_senders
  - storage_location
  - inapp_num_likes
  - inapp_num_dislikes
  - inapp_num_reactions
  - inapp_num_comments
  - inapp_num_playlists
  - inapp_likes
  - inapp_dislikes
  - inapp_reactions
  - inapp_comments
  - inapp_playlists
  - album_name
  - released_year
  - released_month
  - released_day
  - in_spotify_playlists
  - in_spotify_charts
  - in_spotify_streams
  - in_spotify_viral
  - in_apple_playlists
  - in_deezer_playlists
  - in_deezer_charts
  - in_shazam_charts
  - bpm
  - key
  - mode
  - genre
  - danceability
  - valence
  - energy
  - acousticness
  - instrumentalness
  - liveness
  - speechiness
  - cover_url
  - streams
🔍 Tracks dataset preview:

,track_id,track_name,artist_names,artist_count,total_likes,total_dislikes,total_reactions,total_comments,likes,dislikes,...,genre,danceability,valence,energy,acousticness,instrumentalness,liveness,speechiness,cover_url,streams
0,630156709279300166916839,Everyday Is Christmas,"[""Sia""]",1,0,0,0,0,[],[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,799239679632816136087581,Drive You Insane,"[""Daniel Di Angelo""]",1,0,0,0,0,[],[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,317966213568013409768079,Shabaye Khat Khati (Prymie.com),"[""Poori""]",1,1,0,1,0,[7081778009],[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,480154602683649733755035,Flawless,"[""The Neighbourhood""]",1,7,1,8,0,"[7732627570, 1913497898, 8000666987, 624476088...",[3089727165],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,552638642383922261022982,I'm Good (Blue),"[""David Guetta"", ""Bebe Rexha""]",2,1,0,1,0,[1350955342],[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

🎤 Artists Dataset: 3912 rows, 17 columns
Column names:
  - artist_id
  - artist_name
  - genre
  - albums
  - tracks
  - num_likes
  - num_dislikes
  - num_reactions
  - num_comments
  - likes
  - dislikes
  - reactions
  - comments
  - popularity
  - followers
  - bio
  - social_links
🔍 Artists dataset preview:

,artist_id,artist_name,genre,albums,tracks,num_likes,num_dislikes,num_reactions,num_comments,likes,dislikes,reactions,comments,popularity,followers,bio,social_links
0,509033537247611754713936,Sia,NaN,NaN,NaN,105,1,39,0,"[{""track_id"": ""439415188315743234670815"", ""use...","[{""track_id"": ""568299741497869803403899"", ""use...","[{""track_id"": ""739985379203213241505348"", ""use...",NaN,NaN,NaN,NaN,NaN
1,816153863542257384598981,Daniel Di Angelo,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,483098577617225597603972,Poori,NaN,NaN,NaN,8,0,0,0,"[{""track_id"": ""317966213568013409768079"", ""use...","{""track_id"": ""554301043805960657536081"", ""user...",NaN,NaN,NaN,NaN,NaN,NaN
3,969480178439236779705901,The Neighbourhood,NaN,NaN,NaN,388,34,333,0,"[{""track_id"": ""84977380326341884098638"", ""user...","[{""track_id"": ""183555223223481858028031"", ""use...","[{""track_id"": ""161233143951977610373716"", ""use...",NaN,NaN,NaN,NaN,NaN
4,252932351420662645721765,David Guetta,NaN,NaN,NaN,7,0,4,0,"[{""track_id"": ""552638642383922261022982"", ""use...","{""track_id"": ""742063294398986408964770"", ""user...","[{""track_id"": ""787171182072912539471076"", ""use...",NaN,NaN,NaN,NaN,NaN

👤 Users Dataset: 783 rows, 49 columns

Column names:
  - user_id
  - chat_id
  - username
  - uploaded_tracks
  - liked_tracks
  - disliked_tracks
  - reacted_tracks
  - commented_tracks
  - num_likes
  - num_dislikes
  - num_reactions
  - num_comments
  - likes_received
  - dislikes_received
  - reactions_received
  - comments_received
  - num_likes_received
  - num_dislikes_received
  - num_reactions_received
  - num_comments_received
  - liked_users
  - disliked_users
  - reacted_users
  - commented_users
  - num_liked_users
  - num_disliked_users
  - num_reacted_users
  - num_commented_users
  - users_liked
  - users_disliked
  - users_reacted
  - users_commented
  - num_users_liked
  - num_users_disliked
  - num_users_reacted
  - num_users_commented
  - role
  - level
  - activities
  - flagged
  - first_name
  - last_name
  - language
  - bio
  - birthdate
  - profile_photos
  - phone_number
  - email
  - gender
🔍 Users dataset preview:

,user_id,chat_id,username,uploaded_tracks,liked_tracks,disliked_tracks,reacted_tracks,commented_tracks,num_likes,num_dislikes,...,flagged,first_name,last_name,language,bio,birthdate,profile_photos,phone_number,email,gender
0,1007372695,274199889,amiraliyaz,"[""417274426960227193769044"", ""2399531985100775...","[""374009545182065493971748"", ""9311447697407872...","[""888548233340782812461963"", ""1540370666288252...","[{""track_id"": ""374009545182065493971748"", ""rea...",[],4,2,...,0,Amirali,Yazdiani_F,en,NaN,NaN,[],NaN,NaN,NaN
1,1012117954,764686177,bieyti,"[""707358083028692203708370""]","[""117098130324144545834689"", ""4500853108754460...","[""403111679616960630092190""]","[{""track_id"": ""117098130324144545834689"", ""rea...",[],40,1,...,0,Behina,NaN,en,NaN,NaN,[],NaN,NaN,NaN
2,1015503542,7137193964,NaN,[],"[""164346522850428622921476"", ""5778834253754382...",[],"[{""track_id"": ""164346522850428622921476"", ""rea...",[],8,0,...,0,NaN,NaN,en,NaN,NaN,[],NaN,NaN,NaN
3,1020408191,1105712231,Amin_Behtooei,"[""10419922356096440410066"", ""57110867695017764...","[""67661069417820172013774"", ""76359898201828900...",[],"[{""track_id"": ""67661069417820172013774"", ""reac...",[],276,0,...,0,Amin Behtooei,NaN,en,NaN,NaN,[],NaN,NaN,NaN
4,1027381117,1379319065,DibaHemmati,"[""431042079668215670026281""]",[],[],[],[],0,0,...,0,Diba,Hemmati,en,NaN,NaN,[],NaN,NaN,NaN

### Starting Cleaning Process: Removing Unnecessary Columns

Because the raw database was originally planned for a much larger project, many fields are either entirely empty (null) or fall out of the context of this specific analytical assignment. To streamline our Exploratory Data Analysis, we will clean the datasets by stripping away these irrelevant features.

**Important Note:** The operations below are executed exclusively on the Pandas DataFrames in memory. The core `data/raw/*` `.csv` files remain strictly unmodified, preserving data integrity.

- **Tracks Dataset:** We will drop the `storage_location` column along with any system columns that come after it. Additionally, we will remove unneeded features like `comments`, `next_track`, and `previous_track`.
- **Artists Dataset:** We will remove null or unpopulated social columns (`comments`, `popularity`, `followers`, `bio`, `social_links`, `genre`, `albums`) and the redundant `tracks` array mapping, as we can join the datasets manually.
- **Users Dataset:** We will drop personal or empty metadata (`bio`, `birthdate`, `profile_photos`, `phone_number`, `email`, `gender`), structural roles (`role`, `level`, `activities`, `flagged`), and unused comment-tracking statistics (`commented_tracks`, `num_comments`, `comments_received`, etc.).

In [3]:
if 'df_tracks' in locals() and 'df_artists' in locals() and 'df_users' in locals():
    
    # -----------------------------------------------------
    # 1. Clean Tracks Dataset
    # -----------------------------------------------------
    columns_to_drop_tracks = ['comments', 'next_track', 'previous_track']
    
    # Locate 'storage_location' and collect all columns from it to the end
    if 'storage_location' in df_tracks.columns:
        loc_index = df_tracks.columns.get_loc('storage_location')
        columns_to_drop_tracks.extend(df_tracks.columns[loc_index:])
        
    df_tracks_trimmed = df_tracks.drop(columns=columns_to_drop_tracks, errors='ignore')
    
    # -----------------------------------------------------
    # 2. Clean Artists Dataset
    # -----------------------------------------------------
    columns_to_drop_artists = [
        'comments', 'popularity', 'followers', 'bio', 'social_links', 
        'genre', 'albums', 'tracks'
    ]
    df_artists_trimmed = df_artists.drop(columns=columns_to_drop_artists, errors='ignore')
    
    # -----------------------------------------------------
    # 3. Clean Users Dataset
    # -----------------------------------------------------
    columns_to_drop_users = [
        'commented_tracks', 'num_comments', 'comments_received', 'num_comments_received', 
        'commented_users', 'num_commented_users', 'users_commented', 'num_users_commented', 
        'role', 'level', 'activities', 'flagged', 'bio', 'birthdate', 
        'profile_photos', 'phone_number', 'email', 'gender'
    ]
    df_users_trimmed = df_users.drop(columns=columns_to_drop_users, errors='ignore')
    
    # -----------------------------------------------------
    # Verification & Sample Outputs
    # -----------------------------------------------------
    print("✅ Unnecessary Columns successfully removed!\n")
    
    print(f"🎵 Cleaned Tracks Dataset: {df_tracks_trimmed.shape[0]} rows, {df_tracks_trimmed.shape[1]} columns")
    display(df_tracks_trimmed.head(2))
    
    print(f"\n🎤 Cleaned Artists Dataset: {df_artists_trimmed.shape[0]} rows, {df_artists_trimmed.shape[1]} columns")
    display(df_artists_trimmed.head(2))
    
    print(f"\n👤 Cleaned Users Dataset: {df_users_trimmed.shape[0]} rows, {df_users_trimmed.shape[1]} columns")
    display(df_users_trimmed.head(2))
    
else:
    print("⚠️ DataFrames not populated. Please run the Data Loading cell first.")

✅ Unnecessary Columns successfully removed!

🎵 Cleaned Tracks Dataset: 10725 rows, 14 columns

,track_id,track_name,artist_names,artist_count,total_likes,total_dislikes,total_reactions,total_comments,likes,dislikes,reactions,sender_chat_ids,sender_usernames,num_senders
0,630156709279300166916839,Everyday Is Christmas,"[""Sia""]",1,0,0,0,0,[],[],[],[0],[null],1
1,799239679632816136087581,Drive You Insane,"[""Daniel Di Angelo""]",1,0,0,0,0,[],[],[],[0],[null],1

🎤 Cleaned Artists Dataset: 3912 rows, 9 columns

,artist_id,artist_name,num_likes,num_dislikes,num_reactions,num_comments,likes,dislikes,reactions
0,509033537247611754713936,Sia,105,1,39,0,"[{""track_id"": ""439415188315743234670815"", ""use...","[{""track_id"": ""568299741497869803403899"", ""use...","[{""track_id"": ""739985379203213241505348"", ""use..."
1,816153863542257384598981,Daniel Di Angelo,0,0,0,0,NaN,NaN,NaN

👤 Cleaned Users Dataset: 783 rows, 31 columns

,user_id,chat_id,username,uploaded_tracks,liked_tracks,disliked_tracks,reacted_tracks,num_likes,num_dislikes,num_reactions,...,num_reacted_users,users_liked,users_disliked,users_reacted,num_users_liked,num_users_disliked,num_users_reacted,first_name,last_name,language
0,1007372695,274199889,amiraliyaz,"[""417274426960227193769044"", ""2399531985100775...","[""374009545182065493971748"", ""9311447697407872...","[""888548233340782812461963"", ""1540370666288252...","[{""track_id"": ""374009545182065493971748"", ""rea...",4,2,6,...,5,"[6649352285, 8667816286, 9364416709, 477214934...",[6582252810],"[{""user_id"": 6649352285, ""reaction"": ""🔥""}, {""u...",37,1,55,Amirali,Yazdiani_F,en
1,1012117954,764686177,bieyti,"[""707358083028692203708370""]","[""117098130324144545834689"", ""4500853108754460...","[""403111679616960630092190""]","[{""track_id"": ""117098130324144545834689"", ""rea...",40,1,41,...,33,"[2094817151, 2804041751, 2377298811, 813769000...",[],"[{""user_id"": 2094817151, ""reaction"": ""❤""}, {""u...",11,0,11,Behina,NaN,en

### ID Simplification Strategy (Refactoring large identifiers)

Currently, the primary keys (`track_id`, `artist_id`, and `user_id`) natively exported from Telegram are unwieldy sequences (e.g., massive numerical identifiers or UUIDs) making statistical groupings less intuitive to debug natively, This was due to the next upcoming project and for security issues there that I desided to go with 16digit-long UUIDs.

To convert our data architecture to a localized layout designed solely for this EDA class:
1. We will **normalize all core IDs** so they increment simply from 1 upwards.
2. If `user_id 9245100023` becomes `1` in the User's Dataset, we must predictably map any track explicitly connected to `uploaded_by_user_id = 9245100023` cleanly over to `1` as well.
3. This exact sequential mapping rule applies symmetrically directly to the Artist tables.

_To maintain architecture maturity locally, this complex dataframe traversal operation has been offloaded into one of our modular Python scripts built inside `src/preprocessing/id_simplifier.py`. We'll just call the functions directly from there!_

In [7]:
import sys

# Explicitly insert the root Project path so Python finds the src folder.
sys.path.append("..") 

# Import our custom simplifier module smoothly and functionally
from src.preprocessing.id_simplifier import simplify_all_ids

if 'df_tracks_trimmed' in locals() and 'df_artists_trimmed' in locals() and 'df_users_trimmed' in locals():

    # Re-map and transform all the linked IDs iteratively via the imported class
    df_tracks_simplified, df_artists_simplified, df_users_simplified = simplify_all_ids(
        df_tracks=df_tracks_trimmed, 
        df_artists=df_artists_trimmed, 
        df_users=df_users_trimmed
    )
    
    print("✅ IDs effectively mapped recursively from 1 incrementally!")
    print("Take a look at the newly sanitized and fully refactored dataset IDs:\n")
    
    display(df_tracks_simplified.head(5))
    display(df_artists_simplified.head(5))
    display(df_users_simplified.head(5))
else:
    print("⚠️ Cleaned DataFrames drop phase not run. Run the above cells linearly first.")

✅ IDs effectively mapped recursively from 1 incrementally!
Take a look at the newly sanitized and fully refactored dataset IDs:

,track_id,track_name,artist_names,artist_count,total_likes,total_dislikes,total_reactions,total_comments,likes,dislikes,reactions,sender_chat_ids,sender_usernames,num_senders
0,1,Everyday Is Christmas,"[""Sia""]",1,0,0,0,0,[],[],[],[0],[null],1
1,2,Drive You Insane,"[""Daniel Di Angelo""]",1,0,0,0,0,[],[],[],[0],[null],1
2,3,Shabaye Khat Khati (Prymie.com),"[""Poori""]",1,1,0,1,0,[519],[],"[{""user_id"": 519, ""reaction"": ""\ud83d\udd25""}]",[0],[null],1
3,4,Flawless,"[""The Neighbourhood""]",1,7,1,8,0,"[569, 76, 593, 442, 623, 230, 594]",[161],"[{""user_id"": 569, ""reaction"": ""\u2764""}, {""use...","[0, 8169944569]","[null, ""ReggieGrumpyBlack""]",2
4,5,I'm Good (Blue),"[""David Guetta"", ""Bebe Rexha""]",2,1,0,1,0,[35],[],"[{""user_id"": 35, ""reaction"": ""\u2764""}]",[0],[null],1

,artist_id,artist_name,num_likes,num_dislikes,num_reactions,num_comments,likes,dislikes,reactions
0,1,Sia,105,1,39,0,"[{""track_id"": 9, ""user_id"": 248}, {""track_id"":...","[{""track_id"": 6165, ""user_id"": 424, ""reaction""...","[{""track_id"": 6523, ""user_id"": 111, ""reaction""..."
1,2,Daniel Di Angelo,0,0,0,0,NaN,NaN,NaN
2,3,Poori,8,0,0,0,"[{""track_id"": 3, ""user_id"": 519}, {""track_id"":...","{""track_id"": 4269, ""user_id"": 311, ""reaction"":...",NaN
3,4,The Neighbourhood,388,34,333,0,"[{""track_id"": 892, ""user_id"": 363}, {""track_id...","[{""track_id"": 6691, ""user_id"": 161}, {""track_i...","[{""track_id"": 6468, ""user_id"": 329, ""reaction""..."
4,5,David Guetta,7,0,4,0,"[{""track_id"": 5, ""user_id"": 35}, {""track_id"": ...","{""track_id"": 2925, ""user_id"": 490, ""reaction"":...","[{""track_id"": 8738, ""user_id"": 707, ""reaction""..."

,user_id,chat_id,username,uploaded_tracks,liked_tracks,disliked_tracks,reacted_tracks,num_likes,num_dislikes,num_reactions,...,num_reacted_users,users_liked,users_disliked,users_reacted,num_users_liked,num_users_disliked,num_users_reacted,first_name,last_name,language
0,1,274199889,amiraliyaz,"[705, 3088, 67, 3376, 2551, 4125, 4126, 4171, ...","[1039, 5999, 6138, 3221]","[6717, 6749]","[{""track_id"": 1039, ""reaction"": ""\u2764""}, {""t...",4,2,6,...,5,"[486, 655, 725, 303, 122, 311, 346, 40, 568, 6...",[477],"[{""user_id"": 486, ""reaction"": ""\ud83d\udd25""},...",37,1,55,Amirali,Yazdiani_F,en
1,2,764686177,bieyti,[9900],"[8723, 8760, 9491, 9515, 9190, 9541, 498, 9546...",[10293],"[{""track_id"": 8723, ""reaction"": ""\u2764\u200d\...",40,1,41,...,33,"[94, 141, 112, 609, 608, 720, 309, 648, 220, 6...",[],"[{""user_id"": 94, ""reaction"": ""\u2764""}, {""user...",11,0,11,Behina,NaN,en
2,3,7137193964,NaN,[],"[1407, 2234, 2472, 2550, 2652, 2686, 820, 3133]",[],"[{""track_id"": 1407, ""reaction"": ""\u2764\u200d\...",8,0,8,...,7,[],[],[],0,0,0,NaN,NaN,en
3,4,1105712231,Amin_Behtooei,"[1950, 2016, 2061, 2132, 2204, 2272, 922, 2432...","[857, 1717, 1977, 2025, 2030, 2049, 2056, 2058...",[],"[{""track_id"": 857, ""reaction"": ""\u2764""}, {""tr...",276,0,279,...,105,"[775, 43, 548, 41, 7, 29, 567, 311, 25, 40, 25...",[160],"[{""user_id"": 775, ""reaction"": ""\u2764\u200d\ud...",92,1,170,Amin Behtooei,NaN,en
4,5,1379319065,DibaHemmati,[4396],[],[],[],0,0,0,...,0,[371],[],"[{""user_id"": 371, ""reaction"": ""\ud83d\udc4d""}]",1,0,1,Diba,Hemmati,en

*You see how much cleaner the data has got but its not ready yet and we have more steps to take!*

### 💾 Saving Processed Data

Now that our datasets are cleaned and the IDs have been simplified, we will save these intermediate results into the `data/processed/` directory. This ensures we have a clean, easily accessible starting point for our upcoming Exploratory Data Analysis (EDA) and visualization steps without needing to re-run the entire cleaning pipeline.

In [9]:
import os

processed_dir = "../data/processed"
os.makedirs(processed_dir, exist_ok=True)

# Save the simplified datasets
df_tracks_simplified.to_csv(f"{processed_dir}/tracks_simplified.csv", index=False)
df_artists_simplified.to_csv(f"{processed_dir}/artists_simplified.csv", index=False)
df_users_simplified.to_csv(f"{processed_dir}/users_simplified.csv", index=False)

print("✅ Simplified datasets successfully saved to data/processed!")

✅ Simplified datasets successfully saved to data/processed!

---
#### 1.3 🥞 Flattening Simple Lists & Handling Null Artifacts
Here we convert simple array-like string properties like `["David Guetta", "Bebe Rexha"]` into comma-separated strings (`"David Guetta, Bebe Rexha"`) so that machine learning and text processing models can consume them efficiently.
Simultaneously, we transform dummy literal representations like `"[null]"` or `"null"` into proper native `NaN` representations to ensure our datasets remain mathematically robust for visualization and feature engineering.

In [11]:
import sys
import importlib
sys.path.append(r"../src/preprocessing")
import flattener
importlib.reload(flattener)
from flattener import flatten_and_clean

# Apply flattening and clean artifacts
df_tracks_simplified2, df_artists_simplified2, df_users_simplified2 = flatten_and_clean(
    df_tracks_simplified, df_artists_simplified, df_users_simplified
)

print("✅ Lists flattened and null artifacts converted to NaN!")

# Display preview of flattened targets in Tracks
display(df_tracks_simplified2[['track_name', 'artist_names', 'sender_usernames', 'sender_chat_ids']].head(10))

# Save Step 2 processed data
df_tracks_simplified2.to_csv(f"{processed_dir}/tracks_simplified2.csv", index=False)
df_artists_simplified2.to_csv(f"{processed_dir}/artists_simplified2.csv", index=False)
df_users_simplified2.to_csv(f"{processed_dir}/users_simplified2.csv", index=False)

✅ Lists flattened and null artifacts converted to NaN!

,track_name,artist_names,sender_usernames,sender_chat_ids
0,Everyday Is Christmas,Sia,NaN,0
1,Drive You Insane,Daniel Di Angelo,NaN,0
2,Shabaye Khat Khati (Prymie.com),Poori,NaN,0
3,Flawless,The Neighbourhood,ReggieGrumpyBlack,"0, 8169944569"
4,I'm Good (Blue),"David Guetta, Bebe Rexha",NaN,0
5,I Like You (A Happier Song) (feat. Doja Cat),Post Malone,NaN,"0, 6432767708"
6,Coffee Cups and Cigarettes‌,Tomo • @resteici,NaN,0
7,Boombastic,Shaggy,NaN,0
8,Snowman,Sia,"javadtwf, Mah13541347","0, 6432767708, 5912022187, 6726195348"
9,we fell in love in october,girl in red,"KhodeZekavat, feft_1107","0, 6432767708, 461394872, 5948035415"

---
#### 1.4 📝 Text Normalization
Consistent text formatting ensures the robustness of future models parsing strings (like `CountVectorizer` or `TF-IDF`), and limits unexpected behaviors caused by invisible trailing whitespaces, random upper/lowercase permutations, and weird symbols.
In this step, we will convert all relevant categorical string columns to **lowercase** and strip any leading or trailing **whitespaces**.

In [12]:
import text_normalizer
importlib.reload(text_normalizer)
from text_normalizer import normalize_texts

# Apply text normalization
df_tracks_final, df_artists_final, df_users_final = normalize_texts(
    df_tracks_simplified2, df_artists_simplified2, df_users_simplified2
)

print("✅ Text features consistently normalized (lowercased and stripped)!")

# Preview the completely final prepared Tracks DataFrame
display(df_tracks_final[['track_name', 'artist_names', 'sender_usernames']].head(10))

# Save Final Processed Data (Ready for Viz/Modeling)
df_tracks_final.to_csv(f"{processed_dir}/tracks_final.csv", index=False)
df_artists_final.to_csv(f"{processed_dir}/artists_final.csv", index=False)
df_users_final.to_csv(f"{processed_dir}/users_final.csv", index=False)

✅ Text features consistently normalized (lowercased and stripped)!

,track_name,artist_names,sender_usernames
0,everyday is christmas,sia,NaN
1,drive you insane,daniel di angelo,NaN
2,shabaye khat khati (prymie.com),poori,NaN
3,flawless,the neighbourhood,reggiegrumpyblack
4,i'm good (blue),"david guetta, bebe rexha",NaN
5,i like you (a happier song) (feat. doja cat),post malone,NaN
6,coffee cups and cigarettes‌,tomo • @resteici,NaN
7,boombastic,shaggy,NaN
8,snowman,sia,"javadtwf, mah13541347"
9,we fell in love in october,girl in red,"khodezekavat, feft_1107"

In [10]:
display(df_tracks_simplified.head(15))
display(df_artists_simplified.head(15))
display(df_users_simplified.head(15))

,track_id,track_name,artist_names,artist_count,total_likes,total_dislikes,total_reactions,total_comments,likes,dislikes,reactions,sender_chat_ids,sender_usernames,num_senders
0,1,Everyday Is Christmas,"[""Sia""]",1,0,0,0,0,[],[],[],[0],[null],1
1,2,Drive You Insane,"[""Daniel Di Angelo""]",1,0,0,0,0,[],[],[],[0],[null],1
2,3,Shabaye Khat Khati (Prymie.com),"[""Poori""]",1,1,0,1,0,[519],[],"[{""user_id"": 519, ""reaction"": ""\ud83d\udd25""}]",[0],[null],1
3,4,Flawless,"[""The Neighbourhood""]",1,7,1,8,0,"[569, 76, 593, 442, 623, 230, 594]",[161],"[{""user_id"": 569, ""reaction"": ""\u2764""}, {""use...","[0, 8169944569]","[null, ""ReggieGrumpyBlack""]",2
4,5,I'm Good (Blue),"[""David Guetta"", ""Bebe Rexha""]",2,1,0,1,0,[35],[],"[{""user_id"": 35, ""reaction"": ""\u2764""}]",[0],[null],1
5,6,I Like You (A Happier Song) (feat. Doja Cat),"[""Post Malone""]",1,0,0,0,0,[],[],[],"[0, 6432767708]",[null],2
6,7,Coffee Cups and Cigarettes‌,"[""Tomo • @resteici""]",1,0,0,0,0,[],[],[],[0],[null],1
7,8,Boombastic,"[""Shaggy""]",1,0,0,0,0,[],[],[],[0],[null],1
8,9,Snowman,"[""Sia""]",1,16,0,19,0,"[248, 65, 424, 734, 252, 311, 447, 490, 569, 5...",[],"[{""user_id"": 248, ""reaction"": ""\u2764\u200d\ud...","[0, 6432767708, 5912022187, 6726195348]","[null, ""javadtwf"", ""Mah13541347""]",4
9,10,we fell in love in october,"[""girl in red""]",1,15,0,15,0,"[154, 175, 338, 648, 327, 499, 214, 240, 695, ...",[],"[{""user_id"": 154, ""reaction"": ""\u2764""}, {""use...","[0, 6432767708, 461394872, 5948035415]","[null, ""KhodeZekavat"", ""feft_1107""]",4
10,11,Suicidal Thoughts,"[""Josh A"", ""Iamjakehill""]",2,0,0,0,0,[],[],[],[0],[null],1
11,12,Would Anyone Care,"[""Citizen Soldier""]",1,0,0,0,0,[],[],[],"[0, 1110153772]","[null, ""zenix_935""]",2
12,13,NEON BLADE,"[""Moon Deity""]",1,0,0,0,0,[],[],[],[0],[null],1
13,14,Catch Fire (Lyrics) - Jenix,"[""Unknown Artist""]",1,0,0,0,0,[],[],[],[0],[null],1
14,15,FAKE LOVE,"[""BTS""]",1,0,0,0,0,[],[],[],[0],[null],1

,artist_id,artist_name,num_likes,num_dislikes,num_reactions,num_comments,likes,dislikes,reactions
0,1,Sia,105,1,39,0,"[{""track_id"": 9, ""user_id"": 248}, {""track_id"":...","[{""track_id"": 6165, ""user_id"": 424, ""reaction""...","[{""track_id"": 6523, ""user_id"": 111, ""reaction""..."
1,2,Daniel Di Angelo,0,0,0,0,NaN,NaN,NaN
2,3,Poori,8,0,0,0,"[{""track_id"": 3, ""user_id"": 519}, {""track_id"":...","{""track_id"": 4269, ""user_id"": 311, ""reaction"":...",NaN
3,4,The Neighbourhood,388,34,333,0,"[{""track_id"": 892, ""user_id"": 363}, {""track_id...","[{""track_id"": 6691, ""user_id"": 161}, {""track_i...","[{""track_id"": 6468, ""user_id"": 329, ""reaction""..."
4,5,David Guetta,7,0,4,0,"[{""track_id"": 5, ""user_id"": 35}, {""track_id"": ...","{""track_id"": 2925, ""user_id"": 490, ""reaction"":...","[{""track_id"": 8738, ""user_id"": 707, ""reaction""..."
5,6,Bebe Rexha,2,0,0,0,"[{""track_id"": 5, ""user_id"": 35}, {""track_id"": ...","{""track_id"": 1083, ""user_id"": 695, ""reaction"":...",NaN
6,7,Post Malone,189,7,98,0,"[{""track_id"": 907, ""user_id"": 602}, {""track_id...","[{""track_id"": 5787, ""user_id"": 292, ""reaction""...","[{""track_id"": 6599, ""user_id"": 119, ""reaction""..."
7,8,Tomo • @resteici,0,0,0,0,NaN,NaN,NaN
8,9,Shaggy,9,0,0,0,"[{""track_id"": 1726, ""user_id"": 737}, {""track_i...","{""track_id"": 5413, ""user_id"": 49, ""reaction"": ...",NaN
9,10,girl in red,43,0,32,0,"[{""track_id"": 10, ""user_id"": 154}, {""track_id""...","{""track_id"": 10, ""user_id"": 734, ""reaction"": ""...","[{""track_id"": 7955, ""user_id"": 623, ""reaction""..."
10,11,Josh A,5,0,0,0,"[{""track_id"": 2776, ""user_id"": 499}, {""track_i...","{""track_id"": 2776, ""user_id"": 282, ""reaction"":...",NaN
11,12,Iamjakehill,0,0,0,0,NaN,NaN,NaN
12,13,Citizen Soldier,0,0,0,0,NaN,NaN,NaN
13,14,Moon Deity,0,0,0,0,NaN,NaN,NaN
14,15,Unknown Artist,1078,17,1457,0,"[{""track_id"": 113, ""user_id"": 280}, {""track_id...","[{""track_id"": 67, ""user_id"": 477}, {""track_id""...","[{""track_id"": 6211, ""user_id"": 463, ""reaction""..."

,user_id,chat_id,username,uploaded_tracks,liked_tracks,disliked_tracks,reacted_tracks,num_likes,num_dislikes,num_reactions,...,num_reacted_users,users_liked,users_disliked,users_reacted,num_users_liked,num_users_disliked,num_users_reacted,first_name,last_name,language
0,1,274199889,amiraliyaz,"[705, 3088, 67, 3376, 2551, 4125, 4126, 4171, ...","[1039, 5999, 6138, 3221]","[6717, 6749]","[{""track_id"": 1039, ""reaction"": ""\u2764""}, {""t...",4,2,6,...,5,"[486, 655, 725, 303, 122, 311, 346, 40, 568, 6...",[477],"[{""user_id"": 486, ""reaction"": ""\ud83d\udd25""},...",37,1,55,Amirali,Yazdiani_F,en
1,2,764686177,bieyti,[9900],"[8723, 8760, 9491, 9515, 9190, 9541, 498, 9546...",[10293],"[{""track_id"": 8723, ""reaction"": ""\u2764\u200d\...",40,1,41,...,33,"[94, 141, 112, 609, 608, 720, 309, 648, 220, 6...",[],"[{""user_id"": 94, ""reaction"": ""\u2764""}, {""user...",11,0,11,Behina,NaN,en
2,3,7137193964,NaN,[],"[1407, 2234, 2472, 2550, 2652, 2686, 820, 3133]",[],"[{""track_id"": 1407, ""reaction"": ""\u2764\u200d\...",8,0,8,...,7,[],[],[],0,0,0,NaN,NaN,en
3,4,1105712231,Amin_Behtooei,"[1950, 2016, 2061, 2132, 2204, 2272, 922, 2432...","[857, 1717, 1977, 2025, 2030, 2049, 2056, 2058...",[],"[{""track_id"": 857, ""reaction"": ""\u2764""}, {""tr...",276,0,279,...,105,"[775, 43, 548, 41, 7, 29, 567, 311, 25, 40, 25...",[160],"[{""user_id"": 775, ""reaction"": ""\u2764\u200d\ud...",92,1,170,Amin Behtooei,NaN,en
4,5,1379319065,DibaHemmati,[4396],[],[],[],0,0,0,...,0,[371],[],"[{""user_id"": 371, ""reaction"": ""\ud83d\udc4d""}]",1,0,1,Diba,Hemmati,en
5,6,389742063,TheRadiantSunChild,"[1292, 3168, 3295, 4208]","[137, 233, 368, 430, 433, 467, 513, 519, 537, ...",[],"[{""track_id"": 137, ""reaction"": ""\u2764\u200d\u...",68,0,72,...,57,"[186, 444, 643, 777, 486, 567, 630, 490, 70, 1...",[],"[{""user_id"": 186, ""reaction"": ""\u2764\u200d\ud...",21,0,24,Mehrsa☀️,NaN,en
6,7,706051179,NaN,[],"[1752, 1896, 1950, 2000, 2061, 2281, 2495, 266...",[],"[{""track_id"": 1752, ""reaction"": ""\ud83d\udd25""...",11,0,11,...,10,[],[],[],0,0,0,NaN,NaN,en
7,8,127472691,fatemeamanati,"[9985, 9993, 6139, 10085, 10208]","[67, 4273, 4276, 4281, 6321, 6323, 6327, 2800,...","[4188, 6359, 6392, 7848, 8163, 5190, 246, 8956...","[{""track_id"": 67, ""reaction"": ""\u2764\u200d\ud...",54,10,66,...,37,"[621, 160, 397, 220, 119, 252, 463, 455, 783, ...","[161, 720, 734, 171]","[{""user_id"": 621, ""reaction"": ""\u2764""}, {""use...",54,4,89,F.am,NaN,en
8,9,7591301108,Yekidmamoliforcaleg,"[5524, 6020, 6026, 6121]","[1147, 5682, 5693, 3932, 3930, 67, 6016, 6025,...",[],"[{""track_id"": 1147, ""reaction"": ""\ud83e\udd1d""...",9,0,9,...,5,"[695, 593, 494, 768, 646, 160, 608, 659, 296, ...",[],"[{""user_id"": 695, ""reaction"": ""\u2764""}, {""use...",10,0,12,Ja,NaN,en
9,10,6576994572,someone_ishara,[5902],"[3222, 3418, 3437, 1706, 3662, 3686, 3868, 400...",[6684],"[{""track_id"": 3222, ""reaction"": ""\u2764\u200d\...",38,1,40,...,20,"[708, 214, 240, 720, 49, 519, 311]",[],"[{""user_id"": 708, ""reaction"": ""\ud83d\udc94""},...",7,0,7,Z,NaN,en
10,11,7332493711,NaN,[],[3325],[],"[{""track_id"": 3325, ""reaction"": ""\ud83d\udd25""}]",1,0,1,...,1,[],[],[],0,0,0,NaN,NaN,en
11,12,5022915958,Freewolf2,[1255],[],[],[],0,0,0,...,0,[],[],"[{""user_id"": 28, ""reaction"": ""\ud83e\udd2f""}]",0,0,1,MAHDI,NaN,en
12,13,7665972932,RoozbehEs,"[3811, 3864, 3908, 4395, 4500, 4640, 4641, 473...","[3597, 3605, 3749, 25, 4447, 4494, 4585, 1866,...",[],"[{""track_id"": 3597, ""reaction"": ""\ud83d\udd25""...",26,0,26,...,25,"[397, 551, 707, 240, 227, 290, 220, 758, 353, ...",[],"[{""user_id"": 397, ""reaction"": ""\u2764""}, {""use...",22,0,32,Roozbeh,NaN,en
13,14,6752799693,aniras6617,"[6199, 6354, 6553, 7194, 7221, 3422, 4250, 859...","[4405, 4422, 3213, 337, 510, 4798, 4803, 61, 4...",[],"[{""track_id"": 4405, ""reaction"": ""\u2764""}, {""t...",109,0,110,...,66,"[240, 14, 119, 707, 522, 248, 162, 551, 695, 1...",[],"[{""user_id"": 240, ""reaction"": ""\u2764\u200d\ud...",51,0,72,Sarina,NaN,en
14,15,1270784850,de_velvine,"[4920, 4924, 5165]","[4806, 5164]",[],"[{""track_id"": 4806, ""reaction"": ""\ud83d\udd25""...",2,0,3,...,3,"[772, 741, 112, 76, 620, 569, 431, 594, 220, 7...",[],"[{""user_id"": 772, ""reaction"": ""\ud83d\udc94""},...",14,0,15,+.A,NaN,en

---
#### 2️⃣ 📊 Data Visualization
*   **Pattern Extraction:** Practice various data visualization techniques to highlight key behavior.
*   **Core Plot Requirements:** Implement Pie charts, Box plots, Line charts, Multi-line charts, Bar charts (Grouped & Stacked), Scatter plots, Bubble charts, and Error bars (to show uncertainty).
*   **Interactive Graphics:** Utilize interactive charts (e.g., using Plotly or Bokeh).
*   **Aesthetic Guidelines:** Every chart must possess a proper title, axis labels, specific ranges, and legends where needed.

---

#### 3️⃣ ⚙️ Feature Engineering
*   **Feature Invention:** Create insightful metrics via mathematical functions, combinations, ratios, and binning.
*   **Temporal Features:** Perform Date/Time transformations on the upload history.
*   **Aggregations:** Aggregate statistics and calculate counts (e.g., user activity metrics).
*   **Feature Selection:** Evaluate the relevance of features via Mutual Information.
*   **Dimensionality Reduction:** Utilize PCA to uncover the core variances in the dataset.
*   **Reflective Question:** Answer: *"When is feature engineering a nice-to-have option, and when is it a must-have?"*

---
#### 4️⃣ 🕸️ Web Scraping (Bonus Task)
*   **Bama.ir Target:** Write a simple script to scrape and extract data for 50 "Samand" cars manufactured after 1385.
*   **Target Fields:** Price, Mileage, Color, Production year, Transmission type (manual/auto), Description.
*   **Deliverables:** Maintain scraping code and export results directly to an Excel (`.xlsx`) file appropriately mapped in the repo.